---
title: "Cortex Ratio and Density analysis"
author: "Ben Davies"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

##Step 1: Load packages and data

```{r}
require(tidyverse)
require(ggExtra)
require(gridExtra)
require(cowplot)
require(gtable)
require(gridExtra)
require(ggpubr)

occupation<-read.csv("FMODEL_OccupationVsAccumulation OccupationModel-table.csv",stringsAsFactors = FALSE,skip=6)
accumulation<-read.csv("FMODEL_OccupationVsAccumulation AccumulationModel-table.csv",stringsAsFactors = FALSE,skip=6)
```


##Step 2: Produce plot from simulation outcomes

```{r}

#subdivide data
occ_a<-subset(occupation,walkers==100)
occ_a<-subset(occ_a,carry_in==0)

occ_b<-subset(occupation,walkers==100)
occ_b<-subset(occ_b,carry_in==1)

acc_a<-subset(accumulation,levy_mu==1)
acc_a<-subset(acc_a,carry_in==0)

acc_b<-subset(accumulation,levy_mu==1)
acc_b<-subset(acc_b,carry_in==1)



par(mfrow=c(2,2))
plot(log(occ_a[,14]),occ_a[,11],pch=16,ylim=c(0,2),xlab="Log Artifacts in Window",ylab="Cortex Ratio", main="Occupation Model (No Carry In)")

plot(log(acc_a[,14]),acc_a[,11],pch=16,ylim=c(0,3),xlab="Log Artifacts in Window",ylab="Cortex Ratio",main="Accumulation Model (No Carry In)")

plot(log(occ_b[,14]),occ_b[,11],pch=16,ylim=c(0,3),xlab="Log Artifacts in Window",ylab="Cortex Ratio", main="Occupation Model (Carry In)")

plot(log(acc_b[,14]),acc_b[,11],pch=16,ylim=c(0,3),xlab="Log Artifacts in Window",ylab="Cortex Ratio",main="Accumulation Model (Carry In)")

###MULTIPLOT####

theme_set(theme_bw())  # pre-set the bw theme.
a <- ggplot(occ_a, aes(log(sum...length.artefact_type...of.patches), cortex_ratio)) + 
  geom_point() + 
  geom_hline(yintercept = 1) +
  ylim(0,3) +
  #theme(legend.position = "none") +
  labs(title = "Occupation Model", x = "", y = "Cortex Ratio") +
  theme(plot.title = element_text(hjust=0.5),
        axis.title.y = element_text(hjust = 0.5,size=8))+
   theme(plot.margin = unit(c(1,0.1,0.1,0.1), "cm"))
 
b <- ggplot(acc_a, aes(log(sum...length.artefact_type...of.patches), cortex_ratio)) + 
  geom_point() + 
  geom_hline(yintercept = 1) +
  ylim(0,3) +
  #theme(legend.position = "none") +
   theme(plot.title = element_text(hjust=0.5)) +
  labs(title = "Accumulation Model", x = "", y = "") +
   theme(plot.margin = unit(c(1,0.1,0.1,0.1), "cm"))
 

c <- ggplot(occ_b, aes(log(sum...length.artefact_type...of.patches), cortex_ratio)) + 
  geom_point() + 
  geom_hline(yintercept = 1) +
  ylim(0,3) +
  #theme(legend.position = "none") +
  labs(title = "", x = "Log Artefacts in Window", y = "Cortex Ratio") +
  theme(axis.title.y = element_text(hjust = 0.5,size=8),
        axis.title.x = element_text(hjust = 0.5,size=8))+
   theme(plot.margin = unit(c(0.1,0.1,0.1,0.1), "cm"))
 
d <- ggplot(acc_b, aes(log(sum...length.artefact_type...of.patches), cortex_ratio)) + 
  geom_point() + 
  geom_hline(yintercept = 1) +
  ylim(0,3) +
  #theme(legend.position = "none") +
  theme(axis.title.x = element_text(hjust = 0.5,size=8))+
  labs(title = "", x = "Log Artefacts in Window", y = "") +
   theme(plot.margin = unit(c(0.1,0.1,0.1,0.1), "cm"))

lab1 <- text_grob("No Carry-In     ",rot=90,size=14) 
lab2 <- text_grob(" Carry-In",rot=90,size=14)
lay<-rbind(c(1,2,3),c(4,5,6))

png(filename="HRQ_CR.png",width=6,height=6,units="in",res=300)
grid.arrange(lab1,a,b,lab2,c,d,layout_matrix=lay,heights=c(4,4),widths=c(0.5,4,4))
dev.off() 

```



